import os
import json
import ollama
import requests
from bs4 import BeautifulSoup

from constants import *
from utils import function_to_tool_schema

MAX_ITERS = 10
SEARCH_URL = "http://localhost:8888/search"
MAX_RESULTS = 10
MAX_CRAWLED_TEXT = 5000


class ResearcherAgent:
  """An agent that can search the web to get useful links and information based on user prompts. This agent can also use tools to enhance its capabilities."""

  def __init__(self, model=MISTRAL_INSTRUCT):
    self.model = model
    self.query_model = QWEN
    self.messages = []  # context

  def create_search_query(self, user_prompt: str):
    prompt = f"""
    You are a helpful assistant with a senior background that generates search queries for google based on user prompts.

    User question:
    {user_prompt}

    Generate a concise search query that would help you find relevant information to answer the user's question. Focus on the main keywords and concepts in the user's prompt.
    Answer only with the search query, without any additional explanation or formatting.
    No "SEARCH QUERY: ...", just the raw search query string to be used directly in a google search.
    """

    print("[researcher]: Generating search query...")
    response = ollama.chat(
      model=self.query_model,
      messages=[{"role": "user", "content": prompt}]
    )
    return response["message"]["content"]

  def web_search(self, search_query: str):
    """
    Uses searxng to get relevant links based on the search query.
    
    Args:
      search_query (str): The search query string generated by the agent.
    Returns:
      A list of links from the search results.
    """

    print(f"[researcher] Searching query: {search_query}")
    params = {
      "q": search_query,
      "format": "json"
    }
    headers = {
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36",
      "Accept": "application/json"
    }

    try:
      response = requests.get(SEARCH_URL, params=params, headers=headers)
      response.raise_for_status()
      data = response.json()
      print(f"[researcher] Search yielded {len(data.get('results', []))} results, using top {MAX_RESULTS}")
      results = [{"title": result["title"], "url": result["url"]} for result in data.get("results", [])[:MAX_RESULTS]]
    except Exception as e:
      print(f"[researcher] Error during web search: {e}")
      results = []

    return results

  def filter_results(self, results, user_prompt, top_k=3):
    """
    Filters search results using the LLM to select the most relevant links.

    Args:
      results (list): A list of search results, where each result is a dict with 'title' and 'url'.
      user_prompt (str): The original user prompt/question.
      top_k (int): The number of top results to return after filtering.
    Returns:
      A filtered list of search results that are most relevant to the user prompt.
    """

    if not results:
      return []

    prompt = f"""
    You are an expert research assistant.

    User question:
    {user_prompt}

    Here are search results:
    {json.dumps(results, indent=2)}

    Select the {top_k} most relevant results for answering the question.

    Return ONLY a JSON list of selected results in the same format:
    [
      {{"title": "...", "url": "..."}}
    ]
    """

    response = ollama.chat(
      model=self.model,
      messages=[{"role": "user", "content": prompt}]
    )

    content = response["message"]["content"]
    try:
      filtered = json.loads(content)
      return filtered[:top_k]
    except:
      print("[researcher] Failed to parse filter_results output, fallback to top_k")
      return results[:top_k]

  def crawl_webpage(self, url: str) -> str:
    """
    Crawls the webpage at the given URL and extracts the main textual content.
    
    Args:
      url (str): The URL of the webpage to crawl.
    Returns:
      A string containing the main textual content of the webpage, cleaned and truncated to a reasonable length.
    """
    print("[researcher] Crawling:", url)
    headers = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"}

    try:
      response = requests.get(url, headers=headers, timeout=10)
      response.raise_for_status()
    except Exception as e:
      print(f"[researcher] Error crawling {url}: {e}")
      return ""

    soup = BeautifulSoup(response.text, "html.parser")

    for tag in soup(["script", "style", "noscript", "header", "footer", "nav", "aside"]):
      tag.decompose()

    article = soup.find("article")
    if article:
      text = article.get_text(separator=" ", strip=True)
    else:
      text = soup.get_text(separator=" ", strip=True)

    text = " ".join(text.split())
    return text[:MAX_CRAWLED_TEXT]

  def summarize_page(self, text: str) -> str:
    """
    Summarizes the crawled webpage content into key points relevant for answering a question.

    Args:
      text (str): The raw text content of the webpage.
    Returns:
      A summary string containing a short summary and key bullet points.
    """

    prompt = f"""
    Summarize the following webpage content into key points relevant for answering a question.

    Content:
    {text}

    Provide:
    - A short summary
    - 3-5 key bullet points
    """

    response = ollama.chat(
      model=self.model,
      messages=[{"role": "user", "content": prompt}]
    )
    return response["message"]["content"]

  # # NOTE: this is a more "agentic" approach, but gets stuck in an infinite loop
  # def research(self, user_prompt: str):
  #   print(f"[researcher] Starting research for: {user_prompt}")

  #   tools = [
  #     function_to_tool_schema(self.create_search_query),
  #     function_to_tool_schema(self.web_search),
  #     function_to_tool_schema(self.filter_results),
  #     function_to_tool_schema(self.crawl_webpage),
  #     function_to_tool_schema(self.summarize_page),
  #   ]

  #   system_prompt = """
  #   You are an autonomous research agent.

  #   Your goal is to answer the user's question by using tools.

  #   You MUST follow this strategy:
  #   1. Generate a search query
  #   2. Search the web
  #   3. Filter relevant results
  #   4. Crawl webpages
  #   5. Summarize content
  #   6. Combine knowledge into a final answer

  #   Rules:
  #   - Always use tools when needed
  #   - Do NOT hallucinate
  #   - Prefer fewer high-quality sources (3 max)
  #   - Once you have enough information, produce the final answer
  #   - Final answer must be well-structured and reference sources (URLs)
  #   """

  #   self.messages = [
  #     {"role": "system", "content": system_prompt},
  #     {"role": "user", "content": user_prompt}
  #   ]

  #   for _ in range(MAX_ITERS):
  #     response = ollama.chat(
  #       model=self.model,
  #       messages=self.messages,
  #       tools=tools
  #     )

  #     msg = response["message"]
  #     print(msg)

  #     # no tool calls
  #     if "tool_calls" not in msg or not msg["tool_calls"]:
  #       self.messages.append(msg)
  #       return msg["content"]

  #     self.messages.append(msg)

  #     for tool_call in msg["tool_calls"]:
  #       func_name = tool_call["function"]["name"]
  #       args = tool_call["function"]["arguments"]

  #       # Ollama sometimes returns string args
  #       if isinstance(args, str):
  #         try:
  #           args = json.loads(args)
  #         except:
  #           args = {}

  #       print(f"[researcher]: tool call {func_name}({args})")
  #       method = getattr(self, func_name)
  #       # ensure correct arguments per function
  #       try:
  #         if func_name == "filter_results":
  #           result = method(
  #             results=args.get("results", []),
  #             user_prompt=user_prompt,
  #             top_k=args.get("top_k", 3)
  #           )
  #         else:
  #           result = method(**args)
  #       except Exception as e:
  #         print(f"[researcher] Tool error: {e}")
  #         result = ""

  #       print(f"[researcher]: tool result: {str(result)[:200]}...")

  #       self.messages.append({
  #         "role": "tool",
  #         "name": func_name,
  #         "content": json.dumps(result)
  #       })

  #   return "Failed to complete research within iteration limit."

  def research(self, user_prompt: str):
    print(f"[researcher] Starting research for: {user_prompt}")

    # search the web
    query = self.create_search_query(user_prompt)
    results = self.web_search(query)
    if not results:
      return "No results found."
    filtered = self.filter_results(results, user_prompt)
    if not filtered:
      filtered = results[:3]  # fallback

    # crawl and summarize
    summaries = []
    for res in filtered:
      url = res["url"]
      text = self.crawl_webpage(url)
      if not text or len(text) < 200:
        continue

      summary = self.summarize_page(text)
      summaries.append({
        "title": res["title"],
        "url": url,
        "summary": summary
      })

    if not summaries:
      return "Failed to extract useful information."

    # final answer
    final_prompt = f"""
    You are a senior researcher.

    User question:
    {user_prompt}

    Here are summarized sources:
    {json.dumps(summaries, indent=2)}

    Provide a well-structured, accurate answer based on the sources.
    Include references to sources where appropriate.
    """

    response = ollama.chat(
      model=self.model,
      messages=[{"role": "user", "content": final_prompt}]
    )
    return response["message"]["content"]
