import os
import json
import requests
import ollama

from constants import *
from utils import function_to_tool_schema

from dotenv import load_dotenv
dotenv_path = os.path.join(os.path.dirname(__file__), '.env')
load_dotenv(dotenv_path)

GOOGLE_API_KEY = os.environ.get("GOOGLE_API_KEY")
GOOGLE_CSE_ID = os.environ.get("GOOGLE_CSE_ID")
SEARCH_URL = "https://www.googleapis.com/customsearch/v1"


class ResearcherAgent:
  """An agent that can search the web to get useful links and information based on user prompts. This agent can also use tools to enhance its capabilities."""

  def __init__(self, model=MISTRAL_INSTRUCT):
    self.model = model
    self.query_model = QWEN
    self.messages = []  # context

  def create_search_query(self, user_prompt: str):
    prompt = f"""
    You are a helpful assistant with a senior background that generates search queries for google based on user prompts.

    User question:
    {user_prompt}

    Generate a concise search query that would help you find relevant information to answer the user's question. Focus on the main keywords and concepts in the user's prompt.
    Answer only with the search query, without any additional explanation or formatting.
    No "SEARCH QUERY: ...", just the raw search query string to be used directly in a google search.
    """

    print("[researcher]: Generating search query...")
    response = ollama.chat(
      model=self.query_model,
      messages=[{"role": "user", "content": prompt}]
    )
    return response["message"]["content"]

  def web_search(self, search_query: str):
    """
    Uses google search API to get relevant links based on the search query.
    
    Args:
      search_query (str): The search query string generated by the agent.
    Returns:
      A list of links from the search results.
    """

    print(f"[researcher] Searching query: {search_query}")
    params = {
      "key": GOOGLE_API_KEY,
      "cx": GOOGLE_CSE_ID,
      "q": search_query
    }

    data = requests.get(SEARCH_URL, params=params).json()
    print(data)
    for item in data.get("items", []):
      print(item["title"])
      print(item["link"])
      print()

    results = [
      {"title": item["title"], "link": item["link"]}
      for item in data.get("items", [])
    ]
    return results


  def research(self, user_prompt: str):
    tools = [
      function_to_tool_schema(self.create_search_query),
      function_to_tool_schema(self.web_search),
    ]
    self.messages.append({"role": "user", "content": user_prompt})

    while True:
      response = ollama.chat(
        model=self.model,
        messages=self.messages,
        tools=tools
      )
      msg = response["message"]
      print(msg)

      if "tool_calls" not in msg or not msg["tool_calls"]:
        self.messages.append(msg)
        return msg["content"]

      self.messages.append(msg)
      for tool_call in msg["tool_calls"]:
        func_name = tool_call["function"]["name"]
        args = tool_call["function"]["arguments"]
        if isinstance(args, str):
          args = json.loads(args)

        print(f"[researcher]: tool call {func_name}({args})")
        method = getattr(self, func_name)
        result = method(**args)
        print(f"[researcher]: tool result: {result}")
        self.messages.append({
          "role": "tool",
          "name": func_name,
          "content": json.dumps(result),
        })
